---
# See https://github.com/jvautier/project-cli
fullname: jvautier/gitlab-api-cli
description: gitlab tiny api client
tags:
  - python
  - cli
  - gitlab
  - api
github:
  has_issues: true
  has_projects: false
  has_wiki: false
